### ISSUE TITLE
terminate called without an active exception

### ISSUE THREAD

**Issue by serverok** [oxen-io/session-push-notification-server#40]
When starting i get the following error

```
push@vps-5b6fc469:~/session-push-notification-server$ /usr/bin/python3 -mspns.hivemind
2023-11-20 16:08:04,498 vps-5b6fc469 spns[119704] INFO Loading config from spns.ini
2023-11-20 16:08:04 vps-5b6fc469 spns[119704] INFO Loaded hivemind X25519 keypair with pubkey f4af2b5774e482701fb4a3703cb8f67006b09c189cb2b36cb18c58c34fbe1079
2023-11-20 16:08:04 vps-5b6fc469 spns[119704] INFO Loaded onionreq X25519 keypair with pubkey d896bc1250e2244178a92edbc854cc9011a4370dd2ca6d1277d5e954dc958d10
2023-11-20 16:08:04 vps-5b6fc469 spns[119704] INFO Starting hivemind
[2023-11-20 16:08:04] [+0.089s] [pg:info|spns/pg.cpp:12] Connecting to postgresql database @ postgresql:///spns
[2023-11-20 16:08:04] [+0.094s] [utils:warning|spns/utils.cpp:67] NOFILE limit is only 1024; increasing to 10000
[2023-11-20 16:08:04] [+0.094s] [hivemind:info|spns/hivemind.cpp:102] Listening for local connections on ipc://./hivemind.sock
terminate called without an active exception
Aborted (core dumped)
push@vps-5b6fc469:~/session-push-notification-server$ 
```

When running service

```
root@vps-5b6fc469:/home/ubuntu# systemctl start spns-hivemind
Job for spns-hivemind.service failed because a fatal signal was delivered causing the control process to dump core.
See "systemctl status spns-hivemind.service" and "journalctl -xeu spns-hivemind.service" for details.
root@vps-5b6fc469:/home/ubuntu# systemctl status spns-hivemind.service
● spns-hivemind.service - Session Push Notification Server -- central push handler (hivemind)
     Loaded: loaded (/etc/systemd/system/spns-hivemind.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: core-dump) since Mon 2023-11-20 16:10:02 UTC; 2s ago
    Process: 119952 ExecStart=/usr/bin/python3 -mspns.hivemind (code=dumped, signal=ABRT)
   Main PID: 119952 (code=dumped, signal=ABRT)
     Status: "Cleaning database"
        CPU: 145ms

Nov 20 16:10:02 vps-5b6fc469 systemd[1]: spns-hivemind.service: Main process exited, code=dumped, status=6/ABRT
Nov 20 16:10:02 vps-5b6fc469 systemd[1]: spns-hivemind.service: Failed with result 'core-dump'.
Nov 20 16:10:02 vps-5b6fc469 systemd[1]: Failed to start Session Push Notification Server -- central push handler (hivemind).
root@vps-5b6fc469:/home/ubuntu# 
```

Any idea how to fix this?

**Comment by jagerman** [comment]
I'd probably need a stack trace (`coredumpctl gdb`, from the `systemd-coredump` package) to get an idea of what's going on here.

**Comment by serverok** [comment]
Thanks, i got this

```
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/python3.10...
(No debugging symbols found in /usr/bin/python3.10)
[New LWP 137171]
[New LWP 137175]
[New LWP 137174]
[New LWP 137173]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/bin/python3 -mspns.hivemind'.
Program terminated with signal SIGABRT, Aborted.
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=139939696570368) at ./nptl/pthread_kill.c:44
44	./nptl/pthread_kill.c: No such file or directory.
[Current thread is 1 (Thread 0x7f463fe77000 (LWP 137171))]
(gdb) 
(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=139939696570368) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=139939696570368) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=139939696570368, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007f463feba476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007f463fea07f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007f463f15cb9e in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007f463f16820c in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007f463f168277 in std::terminate() () from /lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00007f463f6cb1db in spns::HiveMind::HiveMind(spns::Config) () from /home/push/session-push-notification-server/spns/core.cpython-310-x86_64-linux-gnu.so
#9  0x00007f463f76206b in ?? () from /home/push/session-push-notification-server/spns/core.cpython-310-x86_64-linux-gnu.so
#10 0x00007f463f6c2b52 in ?? () from /home/push/session-push-notification-server/spns/core.cpython-310-x86_64-linux-gnu.so
#11 0x00007f463f6ae78b in ?? () from /home/push/session-push-notification-server/spns/core.cpython-310-x86_64-linux-gnu.so
#12 0x000055be25103e0e in ?? ()
#13 0x000055be250fa5eb in _PyObject_MakeTpCall ()
#14 0x000055be25112910 in ?? ()
#15 0x000055be2510ed67 in ?? ()
#16 0x000055be250fa98b in ?? ()
#17 0x00007f463f6b0e5d in ?? () from /home/push/session-push-notification-server/spns/core.cpython-310-x86_64-linux-gnu.so
#18 0x000055be250fa5eb in _PyObject_MakeTpCall ()
#19 0x000055be250f2c66 in _PyEval_EvalFrameDefault ()
#20 0x000055be2510470c in _PyFunction_Vectorcall ()
#21 0x000055be250ece0d in _PyEval_EvalFrameDefault ()
#22 0x000055be251dde56 in ?? ()
#23 0x000055be251ddcf6 in PyEval_EvalCode ()
#24 0x000055be251e3b0d in ?? ()
#25 0x000055be25104969 in ?? ()
#26 0x000055be250ece0d in _PyEval_EvalFrameDefault ()
#27 0x000055be2510470c in _PyFunction_Vectorcall ()
#28 0x000055be250ece0d in _PyEval_EvalFrameDefault ()
#29 0x000055be2510470c in _PyFunction_Vectorcall ()
#30 0x000055be251fb5dd in ?? ()
#31 0x000055be251fa288 in Py_RunMain ()
#32 0x000055be251d0cad in Py_BytesMain ()
#33 0x00007f463fea1d90 in __libc_start_call_main (main=main@entry=0x55be251d0c70, argc=argc@entry=2, argv=argv@entry=0x7ffda30904f8) at ../sysdeps/nptl/libc_start_call_main.h:58
#34 0x00007f463fea1e40 in __libc_start_main_impl (main=0x55be251d0c70, argc=2, argv=0x7ffda30904f8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffda30904e8)
    at ../csu/libc-start.c:392
#35 0x000055be251d0ba5 in _start ()
(gdb) 
```

**Comment by noobinandroid** [comment]
Any luck with this? Getting same error, running ubuntu 22

**Comment by noobinandroid** [comment]
> I'd probably need a stack trace (`coredumpctl gdb`, from the `systemd-coredump` package) to get an idea of what's going on here.

Are there any fixes on this ?
